"""Actualizar modelo Reserva

Revision ID: 33905d80131a
Revises: 
Create Date: 2024-11-16 22:34:27.698875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '33905d80131a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tipo_reserva',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('reserva', sa.Column('id_tipo_reserva', sa.Uuid(), nullable=False))
    op.alter_column('reserva', 'fecha',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.create_foreign_key(None, 'reserva', 'tipo_reserva', ['id_tipo_reserva'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reserva', type_='foreignkey')
    op.alter_column('reserva', 'fecha',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)
    op.drop_column('reserva', 'id_tipo_reserva')
    op.drop_table('tipo_reserva')
    # ### end Alembic commands ###
